### ISSUE TITLE
left-right flip when plotting

### ISSUE THREAD

**Issue by zye1996** [mike4192/spot_micro_kinematics_python#2]
Hi, 

When I tried to plot the kinematic image, I am having a problem matching leg angles with corresponding legs. It seems the left and right side of the figure is flipped.

eg. when I set y=14, I get angles from the right-back leg as (0.0, -53.05, 98.06), unit in degrees. and the plot is as follow:
![image1](https://user-images.githubusercontent.com/28901953/147399862-07d682e8-df9f-41c9-9bce-6c3879cf3bcc.png)

when I set the angle phi=30, I get angles from the right-back leg as (-32.20, -54.43, 100.48) and the figure is plotted as follow:
![image2](https://user-images.githubusercontent.com/28901953/147399910-6810546e-cfeb-4eaa-9de8-7c404e05d279.png)

the leap angle 98.06 vs 100.48 is close, but the difference is clear from the plot. I was wondering whether the left and right legs are flipped in the code?

**Comment by mike4192** [comment]
There is indeed an issue here, however I think it's just a plotting issue.

I believe the leg angles for each leg are correct, however the plotted visualization is incorrect, and effectively swaps left and right legs, and also reverses the phi roll angle. 

This is because for plotting I swapped y and z values to get it to plot more nicely, however this probably ends up reversing some coordinate systems in ways I didn't expect. Looking into a fix...

**Comment by mike4192** [comment]
Should be resolved now with the merged PR
